import type { Octokit } from '@octokit/rest';
import type { CodeFix } from '../types.js';

export interface CreatePRResult {
  prNumber: number;
  prUrl: string;
  branch: string;
}

/**
 * Create a branch, commit fixes, and open a PR.
 * Uses the Git Tree API for multi-file atomic commits.
 */
export async function createFixPR(
  octokit: Octokit,
  owner: string,
  repo: string,
  baseBranch: string,
  fix: CodeFix,
  reviewers: string[],
): Promise<CreatePRResult> {
  const branchName = `auto-fix/${Date.now()}`;

  // 1. Get the base branch ref
  const { data: refData } = await octokit.git.getRef({
    owner,
    repo,
    ref: `heads/${baseBranch}`,
  });
  const baseSha = refData.object.sha;

  // 2. Get the base commit's tree
  const { data: commitData } = await octokit.git.getCommit({
    owner,
    repo,
    commit_sha: baseSha,
  });
  const baseTreeSha = commitData.tree.sha;

  // 3. Create a new tree with the fixes
  const treeItems = fix.fixes.map((f) => ({
    path: f.path,
    mode: '100644' as const,
    type: 'blob' as const,
    content: f.fixedContent,
  }));

  const { data: newTree } = await octokit.git.createTree({
    owner,
    repo,
    base_tree: baseTreeSha,
    tree: treeItems,
  });

  // 4. Create a commit
  const { data: newCommit } = await octokit.git.createCommit({
    owner,
    repo,
    message: `${fix.prTitle}\n\n${fix.explanation}`,
    tree: newTree.sha,
    parents: [baseSha],
  });

  // 5. Create the branch ref
  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: newCommit.sha,
  });

  // 6. Create the PR
  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title: fix.prTitle,
    body: fix.prBody + '\n\n---\n*This PR was auto-generated by the CI/CD Self-Healing Agent.*',
    head: branchName,
    base: baseBranch,
  });

  // 7. Request reviewers
  if (reviewers.length > 0) {
    await octokit.pulls.requestReviewers({
      owner,
      repo,
      pull_number: pr.number,
      reviewers,
    });
  }

  return {
    prNumber: pr.number,
    prUrl: pr.html_url,
    branch: branchName,
  };
}
